### ISSUE TITLE
input_network_encoder.cpp binds function "decode" with too many arguments

### ISSUE THREAD

**Issue by Razoric480** [GodotNetworking/network_synchronizer#26]
Or script_decode is defined as having too few.

`input_network_encoder.cpp` defines "decode" with one too many arguments, resulting in an error in godot's debugger. "Method definition provides more arguments than the method actually has `InputNetwokEncoder::decode`".

```c++
ClassDB::bind_method(D_METHOD("decode", "buffer", "inputs"), &InputNetworkEncoder::script_decode);
Array script_decode(Object *p_buffer) const;
```

cc @AndreaCatania

**Comment by AndreaCatania** [comment]
Nice catch, fixed with: https://github.com/GodotNetworking/network_synchronizer/pull/29
